# Default state/config values for MVP loader.

E_bat_0: 6.0
E_max: 13.5
P_ch_max: 4.0
P_dis_max: 4.0
eta_ch: 0.95
eta_dis: 0.95

tfrigo: 4.0
Tmin: 20.0
Tmax: 25.0

# Optimizer objective and network limits
C_L: 2.0
C_bat: 0.005
C_emissions_grid: 1.0
C_emissions_PV: 0.02
P_g_max_import: 7.0
P_g_max_export: 4.0
